"""email verfication

Revision ID: 71773e73c420
Revises: 803c433dc2f4
Create Date: 2025-06-23 14:31:01.428531

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes



from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71773e73c420'
down_revision: Union[str, Sequence[str], None] = '803c433dc2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',   
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('user_id', sa.Integer, sa.ForeignKey('sys_users.id'), nullable=False),
    sa.Column('token', sa.String, unique=True, index=True, nullable=False),
    sa.Column('created_at', sa.DateTime, default=sa.func.now(), nullable=False),
    sa.Column('type', sa.String, default='email_verification', nullable=False),
    sa.Column('expires_at', sa.DateTime, nullable=False),
    sa.Column('is_used', sa.Boolean, default=False, nullable=False),
    )
    
    
 

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('email_verifications')

    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
